spring.application.name=farm
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/farmdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:farmuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:farmpassword}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
server.port=8080
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=6379
